living-room:
  image: homeassistant/home-assistant
  volumes:
    - ${ha_configs}/living-room:/usr/src/app/config
  hostname: living-room

family-room:
  image: homeassistant/home-assistant
  volumes:
    - ${ha_configs}/family-room:/usr/src/app/config
  hostname: family-room

master-bedroom:
  image: homeassistant/home-assistant
  volumes:
    - ${ha_configs}/master-bedroom:/usr/src/app/config
  hostname: master-bedroom

nginx:
  image: nginx
  volumes:
    - ${ha_configs}/nginx:/etc/nginx
  links:
    - living-room:living-room
    - family-room:family-room
    - master-bedroom:master-bedroom
  ports:
    - 80:80
    - 3128:3128