living-room:
  image: homeassistant/home-assistant
  volumes:
    - ${ha_configs}/living-room:/config
  hostname: living-room

family-room:
  image: homeassistant/home-assistant
  volumes:
    - ${ha_configs}/family-room:/config
  hostname: family-room

master-bedroom:
  image: homeassistant/home-assistant
  volumes:
    - ${ha_configs}/master-bedroom:/config
  hostname: master-bedroom
  ports:
    - 8300:8300
    - 8301:8301

nginx:
  image: nginx
  volumes:
    - ${ha_configs}/nginx:/etc/nginx
  links:
    - living-room:living-room
    - family-room:family-room
    - master-bedroom:master-bedroom
  ports:
    - 80:80