main:
  image: homeassistant/home-assistant
  volumes:
    - ${ha_configs}/main:/config
  hostname: main
  ports:
    - 8303:8303
  network_mode: host

master-bedroom:
  image: homeassistant/home-assistant
  volumes:
    - ${ha_configs}/master-bedroom:/config
  hostname: master-bedroom

remote:
  image: homeassistant/home-assistant
  volumes:
    - ${ha_configs}/remote:/config
  hostname: remote

nginx:
  image: nginx
  volumes:
    - ${ha_configs}/nginx:/etc/nginx
  links:
    - living-room:living-room
    - family-room:family-room
    - master-bedroom:master-bedroom
    - remote:remote
  ports:
    - 80:80