.catalog:
  name: Gitlab Community
  version: 8.5.1-0
  description: |
    "Gitlab: An open source git repository manager (https://about.gitlab.com/)"
  minimum_rancher_version: v0.56.0
  maintainer: "Stefan Legg <>"
  uuid: gitlab-1
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname"
      label: "Hostname:"
      required: true
      default: "git.example.com"
      type: "string"

gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

gitlab-data:
  scale: 1
  retain_ip: true