.catalog:
  name: "Gitlab"
  version: "0.1"
  description: |
    "Gitlab: An open source git repository manager (https://about.gitlab.com/)"
  uuid: gitlab-0
  minimum_rancher_version: v0.44.0
  questions:
    - variable: "DB_USER"
      label: "PostgreSQL DB User"
      description: "Postgres Admin User"
      type: "string"
      required: true
      default: "gitlab"
    - variable: "DB_PASS"
      label: "PostgreSQL Root Password"
      description: "Postgres Admin Password"
      type: "string"
      required: true
    - variable: "DB_NAME"
      label: "PostgreSQL Database"
      description: "PostgreSQL Database Name"
      type: "string"
      required: true
      default: "gitlabhq_production"
    - variable: "GITLAB_SECRET_KEY"
      label: "Gitlab's random secret key"
      description: "A Secret key"
      type: "string"
      required: true
    - variable: "GITLAB_TZ"
      label: "Gitlab's Timezone"
      description: "Timezone setting for Gitlab"
      type: "string"
      required: true
      default: "Kolkata"
    - variable: "DOCKER_TZ"
      label: "Docker container's Timezone"
      description: "Timezone setting for Docker"
      type: "string"
      required: true
      default: "Asia/Kolkata"