Living-Room:
  volumes:
    - /home/rancher/scripts/Egon/HA_Configs/living-room:/usr/src/app/config
  build: .
  dockerfile: LivingRoom

Home-Assist-Web-UI:
  ports:
  - 80:8123
  labels:
    io.rancher.loadbalancer.target.Family-Room: family-room.egonspangler.com:80=8123
    io.rancher.loadbalancer.target.Living-Room: living-room.egonspangler.com:80=8123
  tty: true
  image: rancher/load-balancer-service
  links:
  - Living-Room:Living-Room
  - Family-Room:Family-Room
  stdin_open: true

Family-Room:
  image: balloob/home-assistant
  volumes:
    - /home/rancher/scripts/Egon/HA_Configs/family-room:/usr/src/app/config
