living-room:
  image: homeassistant/home-assistant
  volumes:
    - living-room:/usr/src/app/config
  hostname: living-room

family-room:
  image: homeassistant/home-assistant
  volumes:
    - family-room:/usr/src/app/config
  hostname: family-room

master-bedroom:
  image: homeassistant/home-assistant
  volumes:
    - master-bedroom:/usr/src/app/config
  hostname: master-bedroom

squid:
  image: sameersbn/squid:3.3.8-19
  volumes:
    - squidconf:/etc/squid3
    - squidspool:/var/spool/squid3
  links:
    - living-room:living-room
    - family-room:family-room
    - master-bedroom:master-bedroom
  ports:
    - 80:80
    - 3128:3128