living-room:
  build: https://raw.githubusercontent.com/acoushawk/rancher-catalog/master/templates/Home-Assistant/0/LivingRoom
  volumes:
    - /home/rancher/scripts/Egon/HA_Configs/living-room:/usr/src/app/config
  hostname: living-room

family-room:
  image: balloob/home-assistant
  volumes:
    - /home/rancher/scripts/Egon/HA_Configs/family-room:/usr/src/app/config
  hostname: family-room

nginx:
  image: nginx
  links:
  - living-room:living-room
  - family-room:family-room
  ports:
  - 80:80
