name: Home Assistant
description: |
  Home Assistant Home Automation Project.
version: 0.17.1
category: "Home Automation"
maintainer: Matt Armstrong
projectURL: https://github.com/acoushawk/rancher-catalog
